device: cpu
asr:
  model_id: openai/whisper-tiny.en
tts:
  max_words_per_query: 8
llm:
  max_tokens: 1024
  max_history: 100
stream_reader:
  source: hw:0
  format: alsa
  chunk_size: 16000
  sample_rate: 16000
  vad_limit: 3
stream_writer:
  dst: default
  format: alsa
  chunk_size: 256
  sample_rate: 22050
